apiVersion: v1
kind: Service
metadata:
  name: consumer-reply-line-user
  namespace: default
  labels:
    app: consumer-reply-line-user
spec:
  type: ClusterIP
  selector:
    app: consumer-reply-line-user
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
