apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-web
  namespace: default
  labels:
    app: portfolio-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-web
  template:
    metadata:
      labels:
        app: portfolio-web
    spec:
      containers:
      - name: portfolio-web
        image: chokchaifa/chokchai-portfolio:v1.0.21-73f9266 # {"$imagepolicy": "flux-system:portfolio-web"}
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /portfolio
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /portfolio
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
