apiVersion: v1
kind: Service
metadata:
  name: portfolio-web
  namespace: default
  labels:
    app: portfolio-web
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  nodePort: 30300
  selector:
    app: portfolio-web
