apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: nginx-image-update
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        Automated image update and reconciler for nginx
        
        Automation name: {{ .AutomationObject }}
        
        Changes:
        {{ range .Changed -}}
        - {{ . }}
        {{ end -}}
    push:
      branch: main
  update:
    path: "./apps/nginx"
    strategy: Setters
