apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: default
  labels:
    app: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
        - name: docs
          # Static Docusaurus site served by nginx. Placeholder tag below is
          # rewritten by Flux image-automation once CI pushes the first real
          # v1.0.0-<run>.<sha> tag.
          image: chokchaifa/docs:v1.2.0-29.1abb3b1 # {"$imagepolicy": "flux-system:docs"}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 20m
              memory: 32Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      restartPolicy: Always
