apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: line-webhook
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: line-webhook
  filterTags:
    pattern: '^v[0-9]+\.[0-9]+\.[0-9]+.*$'
  policy:
    semver:
      range: '>=0.0.0-0'
