apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: worker-reminder-scheduler
  app.kubernetes.io/instance: worker-reminder-scheduler
  app.kubernetes.io/component: backend
