---
apiVersion: v1
kind: Service
metadata:
  name: weave-gitops-proxy
  namespace: default
  labels:
    app: weave-gitops-proxy
spec:
  type: ClusterIP
  ports:
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Endpoints
metadata:
  name: weave-gitops-proxy
  namespace: default
subsets:
- addresses:
  - ip: 10.152.183.1  # This needs to be the actual service IP, we'll get it dynamically
  ports:
  - port: 9001
    name: http
