apiVersion: apps/v1
kind: Deployment
metadata:
  name: weave-gitops
  namespace: flux-system
  labels:
    app: weave-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weave-gitops
  template:
    metadata:
      labels:
        app: weave-gitops
    spec:
      containers:
      - name: weave-gitops
        image: ghcr.io/weaveworks/wego-app:v0.35.0
        ports:
        - containerPort: 9001
        env:
        - name: WEAVE_GITOPS_FEATURE_TENANCY
          value: "true"
        - name: WEAVE_GITOPS_FEATURE_CLUSTER
          value: "true"
        args:
        - --log-level=info
        - --insecure
        - --insecure-no-authentication-user=admin
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 9001
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 9001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
