apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 60m
  releaseName: weave-gitops
  chart:
    spec:
      chart: weave-gitops
      version: "4.0.36"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  values:
    # Basic configuration
    replicaCount: 1
    
    # Service configuration
    service:
      type: ClusterIP
      port: 9001
      
    # Ingress will be handled separately
    ingress:
      enabled: false
      
    # Resource limits
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
        
    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      
    # RBAC
    rbac:
      create: true
      
    # Service account
    serviceAccount:
      create: true
      
    # Additional configuration
    envVars:
      - name: WEAVE_GITOPS_FEATURE_TENANCY
        value: "true"
      - name: WEAVE_GITOPS_FEATURE_CLUSTER
        value: "true"
