apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: weave-gitops
      version: "4.0.36"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
      interval: 1m
  values:
    # Basic configuration for Weave GitOps
    replicaCount: 1
    
    # Resources
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 64Mi
    
    # Security context
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    
    # Service configuration
    service:
      type: NodePort
      port: 9001
      nodePort: 30090
    
    # Ingress configuration - enable and configure properly
    # ingress:
    #   enabled: true
    #   className: "nginx"
    #   annotations: {}  # Remove rewrite rules since app handles subpath internally
    #   hosts:
    #     - host: ""
    #       paths:
    #         - path: /
    #           pathType: Prefix
    #   tls: []
    
    # RBAC
    rbac:
      create: true
      impersonationResourceNames: ["admin"]
    
    # ServiceAccount
    serviceAccount:
      create: true
      annotations: {}
      name: ""
    
    # Additional configuration
    logLevel: info
    
    # Admin user (password should be configured via secret)
    adminUser:
      create: true
      username: admin
      # passwordHash should be set via a secret or encrypted values
      # Generate with: echo -n "your-password" | bcrypt-tool or htpasswd -bnBC 12 "" your-password | tr -d ':\n'
      passwordHash: "$2y$12$XVS.VFfwRXotwLTXewSjFeeZ40Z/YiLOwW3sN34kY7XTn2PHd7edG"
    
    # Notification configuration (optional)
    # notifications:
    #   enabled: false
