apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - helmrepository.yaml
  - helmrelease.yaml
  # - ingress.yaml  # Disabled - using main homelab ingress instead
