apiVersion: v1
kind: Service
metadata:
  name: weave-gitops
  namespace: flux-system
  labels:
    app: weave-gitops
spec:
  type: ClusterIP
  ports:
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: http
  selector:
    app: weave-gitops
