apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: nginx-default
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nginx
  policy:
    semver:
      range: ">=1.25.0"
  filterTags:
    pattern: '^(?P<version>\d+\.\d+\.\d+)$'
    extract: '$version'
