apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: line-webhook
  app.kubernetes.io/instance: line-webhook
  app.kubernetes.io/component: backend
