apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Monitoring and observability components

resources:
  - weave-gitops  # GitOps dashboard for Flux CD

# Future monitoring components:
# - prometheus    # Metrics collection
# - grafana       # Dashboards and visualization  
# - loki          # Log aggregation
