apiVersion: v1
kind: Service
metadata:
  name: consumer-llm-processor
  namespace: default
  labels:
    app: consumer-llm-processor
spec:
  type: ClusterIP
  selector:
    app: consumer-llm-processor
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
