# Cloudflare Tunnel Configuration, we need to run map ingress manually
tunnel: 1
credentials-file: /home/chokchai/.cloudflared/8df3c19b-430d-47d3-8e84-c671e006149a.json

ingress:
  - hostname: portfolio.chokchai-dev.xyz
    service: http://127.0.0.1:30300   # Portfolio Next.js NodePort

  - hostname: nginx.chokchai-dev.xyz
    service: http://127.0.0.1:30080   # Nginx NodePort

  - hostname: weaver-gitops.chokchai-dev.xyz
    service: http://127.0.0.1:30090   # GitOps NodePort

  # Catch-all for any other requests
  - service: http_status:404