apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: core
  labels:
    app: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
      name: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: core
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: core
  labels:
    app: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
      name: postgres
